# This workflow will sync the App Service in the secondary region with the primary site

on: [workflow_dispatch]

name: Sync Secondary App Service

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check Out
      uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v1
      with:
        inlineScript: ./SyncSecondary.ps1 -resourceGroupName nimccfta-ibwc-rg -webappname nimccfta-ibwc -targetResourceGroupName nimccfta-ibwc2-rg -targetWebappName nimccfta-ibwc2 -trafficManagerProfileName nimccfta-ibwc -trafficManagerEndpoint ibwc-northcentral -slotName staging
        azPSVersion: "latest"
